server:
  port: 8761
  
security:
  basic:
    enabled: true
  user:
    name: user
    password: password

# eurker
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}:${random.value}
  client:
    enabled: true
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false

#turbine:
#  appConfig: gin-gateway,banbu-v3
#  aggregator:
#    clusterConfig: GIN-GATEWAY,BANBU-V3